
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CRB
{

using System;
    using System.Collections.Generic;
    
public partial class beds
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public beds()
    {

        this.Electronic_medical_card = new HashSet<Electronic_medical_card>();

    }


    public int id_bed { get; set; }

    public int num_bed { get; set; }

    public string status_bed { get; set; }

    public int id_room { get; set; }



    public virtual hospital_rooms hospital_rooms { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Electronic_medical_card> Electronic_medical_card { get; set; }

}

}
