
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CRB
{

using System;
    using System.Collections.Generic;
    
public partial class OMS_policy
{

    public int id_OMS { get; set; }

    public string region { get; set; }

    public string insurance_company { get; set; }

    public string policy_number { get; set; }

    public System.DateTime start_date { get; set; }

    public System.DateTime end_date { get; set; }

    public int id_patient { get; set; }



    public virtual Patient Patient { get; set; }

}

}
