
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CRB
{

using System;
    using System.Collections.Generic;
    
public partial class OtchetPost2024
{

    public string Surname { get; set; }

    public string First_name { get; set; }

    public string Patronymic { get; set; }

    public string kod_diagnosis { get; set; }

    public string name_diagnosis { get; set; }

    public System.DateTime date_receipt { get; set; }

    public Nullable<System.DateTime> date_discharge { get; set; }

    public string name { get; set; }

    public int id_case { get; set; }

}

}
